# Use official OpenJDK image
FROM openjdk:17-jdk-slim

# Set working directory in the container
WORKDIR /app

COPY target/Fetch_HomeWorkExample-0.0.1-SNAPSHOT.jar app.jar

# Command to run the application
CMD ["java", "-jar", "receipt-processor.jar"]

# Expose port 8080 to access the application
EXPOSE 8080
